/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      sans: ["Roboto", "Helvetica", "Noto Sans TC", "sans-serif"],
      serif: ["Roboto", "Helvetica", "Noto Sans TC", "serif"],
    },
    extend: {},
    colors: {
      transparent: "transparent",
      current: "currentColor",
      main: "#7F6C5F",
      dark: "#595959",
      gray: "#7F7F7F",
      light: "#E4DFDC",
      info: "#71B9B1",
      alart: "#F66178",
      highlight: "#EAB25F",
      blue: "#3F8BB7",
      dark_blue: "#0F4C83",
      white: "#fff",
      background: "#F5F5F5",
      unselected: "#B3A59C",
    },
  },
  plugins: [
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("daisyui"),
  ],
  daisyui: {
    themes: [
      "cupcake",
      "cmyk",
      "light",
      "dark",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
};
